version: '3.8'

services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infinite-pokedex-crawler
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - CDN_BUCKET_URL=${CDN_BUCKET_URL}
      - CRAWL_RATE_LIMIT=${CRAWL_RATE_LIMIT:-1000}
    volumes:
      - ./data/cache:/app/data/cache
      - ./data/output:/app/data/output
    ports:
      - '3000:3000'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infinite-pokedex-dev
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      - '5173:5173'
    command: npm run dev
